---
stages:
  - lint
  - deploy

image:
  name: docker.io/willhallonline/ansible:2.13-alpine-3.16

yaml-lint:
  stage: lint
  image: docker.io/cytopia/yamllint:latest
  before_script:
    - yamllint -v
  script:
    - yamllint -c .yamllint ansible/*.yml ./configuration/*.yml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - when: never
  interruptible: true

deploy_nonprod:
  stage: deploy
  tags:
    -  nonprod_runner
  before_script:
    - sed -i "s|{{CBS_DEV_API_KEY}}|$API_KEY_DEV|g" ./configuration/nonprod.yml
    - sed -i "s|{{CBS_UAT_API_KEY}}|$API_KEY_UAT|g" ./configuration/nonprod.yml
    - chmod 755 ./ansible && cd ./ansible
    - echo $NONPROD_SSH_KEY | base64 -d | tr -d '\r' > ./ssh.key
    - chmod 600 ./ssh.key
  script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook main.yml -b -e 'target_env=gatus_nonprod' -u opc --key-file=./ssh.key
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual

deploy_prod:
  stage: deploy
  tags:
    -  prod_runner
  before_script:
    - sed -i "s|{{API_KEY}}|$API_KEY_PROD|g" ./configuration/prod.yml
    - chmod 755 ./ansible && cd ./ansible
    - echo $PROD_SSH_KEY | base64 -d | tr -d '\r' > ./ssh.key
    - chmod 600 ./ssh.key
  script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook main.yml -b -e 'target_env=gatus_prod' -u opc --key-file=./ssh.key
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual